## 00. PyTorch Fundamentals


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


##Introduction to Tensors

##Creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [ ]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
Matrix = torch.tensor([[1,2],[4,5],[7,8]])
Matrix

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([3, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [3,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [3, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [3, 4, 5]])

###Random Tensors

Why Random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)

random_tensor



tensor([[0.4720, 0.5271, 0.5140, 0.3912],
        [0.2732, 0.7920, 0.6399, 0.0180],
        [0.5145, 0.2241, 0.6082, 0.9369]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create an random tensor with similiar shape to an image

random_image_size_tensor = torch.rand(size = (224,224,3)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
#create a tensor of all zeros

zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a range of tensors and tensors-like


In [ ]:
#Use torch.range()
one_to_ten1 = torch.arange(start = 1, end = 1000, step = 50)
one_to_ten1

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [ ]:
#creating tensors like
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
ten_zeros = torch.ones_like(input = one_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Data Types

In [ ]:
#Float 32 Tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.long, #datatype = the tenso (e.g float32, float16)
                               device = "cpu", #device = cpu, gpu or tpu
                               requires_grad = False)#whether to track the gradients or not with tensors operators

print(float_32_tensor)
print(float_32_tensor.dtype)
float_32_tensor

tensor([3, 6, 9])
torch.int64


tensor([3, 6, 9])

In [ ]:
float_32_tensor.dtype

torch.int64

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9, 36, 81])

###Getting Information from Tensors

1. Tensors not right datatype = to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device rom a tensor, can use `tensor.device`

In [ ]:
#create a tensor

some_tensor = torch.rand(3,4)
some_tensor = torch.tensor(some_tensor, dtype = torch.float16, device = "cpu")
print(some_tensor)



tensor([[0.7627, 0.1582, 0.3057, 0.3567],
        [0.1260, 0.1527, 0.3848, 0.3726],
        [0.9155, 0.8950, 0.1842, 0.4275]], dtype=torch.float16)


<ipython-input-29-cf34d1a9a62f>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  some_tensor = torch.tensor(some_tensor, dtype = torch.float16, device = "cpu")


In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7627, 0.1582, 0.3057, 0.3567],
        [0.1260, 0.1527, 0.3848, 0.3726],
        [0.9155, 0.8950, 0.1842, 0.4275]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulationg Tensors(tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [ ]:
#creating a tensor for addition

tensor = torch.tensor([1,2,3])
tensor + 20


tensor([21, 22, 23])

In [ ]:
#tensor multiplication
tensor * 100

tensor([100, 200, 300])

In [ ]:
#try out PyTorch in in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (2, 3)` will work

2. The resultiing matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
#element wise multiplication

print (tensor, '*', tensor)

print (f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.36 ms, sys: 1.07 ms, total: 2.43 ms
Wall time: 2.21 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 647 µs, sys: 0 ns, total: 647 µs
Wall time: 561 µs


tensor(14)

### One of the common errors in Deep Learning: Shape Errors

In [ ]:
#Shapes for matrix multiplication

tensor_A  = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B  = torch.tensor([[7, 8],
                          [9, 10],
                          [11, 12]])
torch.mm(tensor_A, tensor_B)
##torch.matmul(tensor_A, tensor_B) #torch.mm is the same as torch.matmul for easier use
# shape error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix the tensor shape issues, we can manipulate the shape of one of the tensors using **transpose**.

Transpose means switching the axes or dimensions of the given tensor



In [ ]:
tensor_B

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

In [ ]:
torch.matmul(tensor_A, tensor_B.T).shape

So, it can be seen that the matrix multiplication can only be carried out, if the tensor_B is transposed or when the inner dimensions are matched



In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

###Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
#create a tensor

x = torch.arange(1, 100, 10)
x


In [ ]:
x.min()

In [ ]:
torch.max(x), x.max()

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
#Find the Sum

torch.sum(x), x.sum()

###Finding the position of min and max


In [ ]:
x

In [ ]:
#Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minumum value occurs
x.argmin()

In [ ]:
x[0]

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

In [ ]:
x[9]

### Reshaping, stacking, squeezing and unsqueezing

- Reshaping - Reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side stack (hstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - adds a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(01., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x
z.shape, x.shape

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
#torch.squeeze() - removes all single dimensions
print(f"Previous tensor : {x_reshaped}")
print(f"Previous Tensor : {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze(dim = 0)
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Tensor : torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
#torch unsqueeze() = adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size= (224, 224, 3)) #[height, width, color_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # (color_channels, height, width)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data fom tensors)
Indexing in PyTorch is similar to indexing with NumPy

In [ ]:
#create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket  (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Indexing on the most inner bracket (last dimension)
x[0, 2, 2]

tensor(9)

In [ ]:
# ":" can also be used to select "all" of a target dimension

x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
  x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## PyTorch tensors and NumPy

NumPy is a popular scientific python numerical computing library.

Due to this, PyToch has functionality to interact with it

* Data in NumPy, want in PyTorch Tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Change the value of array, what will this do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to `numpy_tensor` ?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In Short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representatioons of the data -> again -> again ..`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3, 3)

tensor([[0.7583, 0.8064, 0.7037],
        [0.6089, 0.8741, 0.2292],
        [0.9943, 0.8131, 0.5855]])

In [ ]:
import torch

#create two random tensors
rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)

tensor([[0.0782, 0.2156, 0.7312, 0.5131],
        [0.2365, 0.5573, 0.2231, 0.6562],
        [0.4200, 0.5391, 0.9192, 0.5789]])
tensor([[0.5892, 0.3185, 0.9154, 0.2046],
        [0.0672, 0.2455, 0.8673, 0.7867],
        [0.6694, 0.1730, 0.9607, 0.6806]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

# Set the random seed
Random_seed = 42
torch.manual_seed(Random_seed)
rand_tensor_C = torch.rand(3, 4)

torch.manual_seed(Random_seed)
rand_tensor_D = torch.rand(3, 4)

print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVidida hardware + PyTorch working behind the scenes

# 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

## 2. Check for GPU access with PyTorch




In [ ]:
# Check for GPU access

import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best to practice to setup device agnostic code.

E.g. run on GPU if available, else default to CPU

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations


In [ ]:
# Create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3], device = "cpu")

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors backk to the CPU

In [ ]:
#if tensor is in GPU, can't transorm it to NumPy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## 00. PyTorch Fundamentals Exercises
1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

The documentation on torch.Tensor.
The documentation on torch.cuda.

### 2. Create a random tensor with shape (7, 7).

In [1]:
import torch

tensor_2 = torch.rand(7,7)
tensor_2

tensor([[0.2766, 0.7103, 0.0802, 0.1199, 0.4991, 0.2200, 0.2580],
        [0.0869, 0.3296, 0.9996, 0.6102, 0.7139, 0.8942, 0.4001],
        [0.6871, 0.5026, 0.1590, 0.4494, 0.3824, 0.9364, 0.6612],
        [0.1914, 0.6830, 0.5232, 0.0098, 0.9177, 0.7202, 0.1544],
        [0.1093, 0.4943, 0.3365, 0.5669, 0.0612, 0.8783, 0.9945],
        [0.2569, 0.1117, 0.0535, 0.2032, 0.0260, 0.0450, 0.2909],
        [0.6634, 0.9743, 0.0498, 0.6337, 0.0369, 0.0762, 0.2446]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [2]:

# Create another random tensor
tensor_a = torch.rand(1, 7)
print(tensor_a.shape, tensor_2.shape)
#inner dimensions must be same for the matrix multiplication
torch.matmul(tensor_a, tensor_2)
# Perform matrix multiplication

torch.Size([1, 7]) torch.Size([7, 7])


tensor([[1.4674, 2.3469, 1.3238, 1.7277, 1.4564, 2.6699, 2.0940]])

### 4. Set the random seed to 0 and do 2 & 3 over again.

In [3]:
import torch

# Set manual seed
manual_seed = 2


# Create two random tensors
torch.manual_seed(manual_seed)
tensor_a = torch.rand(7, 1, device = "cpu")  # Shape (7, 1)

torch.manual_seed(manual_seed)
tensor_b = torch.rand(1, 1, device = "cpu")  # Shape (1, 1)

# Perform matrix multiplication
result = torch.matmul(tensor_a, tensor_b)

# Print the result and shape
print(result, result.shape)

tensor([[0.3779],
        [0.2342],
        [0.3916],
        [0.2916],
        [0.4386],
        [0.3805],
        [0.2720]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [4]:
# Set random seed on the GPU

torch.manual_seed(1234)

if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)

In [5]:
# Set random seed

manual_seed = 1234
torch.manual_seed(manual_seed)

# Check for access to GPU
if torch.cuda.is_available():
    print("GPU is available!")
else:
    print("GPU is not available.")
# Create two random tensors on GPU
torch.cuda.manual_seed(manual_seed)
tensor_a = torch.rand(2, 3).to("cuda")
torch.cuda.manual_seed(manual_seed)
tensor_b = torch.rand(2, 3).to("cuda")

tensor_a, tensor_b

GPU is available!


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [6]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_a, tensor_b.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
maximum = result.max()

# Find min
minimum = result.min()

print(f"Maximum value: {maximum}")
print(f"Minimum value: {minimum}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
max_idx = result.argmax()

# Find arg min
min_idx = result.argmin()

print(f"Index where max value occurs: {max_idx}")
print(f"Index where min value occurs: {min_idx}")
#

Index where max value occurs: 3
Index where min value occurs: 0


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [13]:
# Set seed
manual_seed = 7

# Create random tensor
torch.manual_seed(manual_seed)
tensor = torch.rand(1, 1, 1, 10)
print(tensor, tensor.shape, sep = "\n")

# Remove single dimensions
tensor_b = tensor.squeeze_()

# Print out tensors and their shapes
print(tensor_b, tensor_b.shape, sep = "\n")


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
